from .user import User
from .doctor import Doctor
from .user_upload import UserUpload
from .user_session import UserSession
from .diagnosis_medicine_mapping import DiagnosisMedicineMapping
from .diagnose_code_table import DiagnoseCodeTable
from .QuestionAbbreviationMap import QuestionAbbreviationMap
from .doctor_transaction import Doctor_Transaction
from .consulting_fee import Consulting_Fee
from .PromoCode import PromoCode
