from .crud_role import role
from .crud_user import user
from .crud_user_role import user_role
from .crud_case import casez
from .crud_session import user_session
from .crud_diagnosis_medicine import diagnosis
from .sms_service import send_otp
from .crud_transactions import doctor_transaction
from .consulting_fee_service import consulting_fee
from .PromoCodeService import promo_code
from .crud_tax import tax
