version: '3.8'

services:
  backend:
    image: latest-15may  # Replace with your backend Docker image name
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      MYSQLCLIENT_CFLAGS: "-I/usr/include/mysql"
      MYSQLCLIENT_LDFLAGS: "-L/usr/lib/x86_64-linux-gnu -lmysqlclient"
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --ssl-keyfile=certificate/generated-private-key.txt --ssl-certfile=certificate/9a07b3ec74f104e1.crt

  frontend:
    image: frontend  # Replace with your frontend Docker image name
    build:
      context: ./SkinWebapp_Admin
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:80"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificate:/etc/nginx/certificate
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend