version: '3.8'

services:
  backend:
    build:
      context: ./  # Path to the directory containing your FastAPI backend Dockerfile
    ports:
      - "8000:8000"  # Expose FastAPI backend on port 8000
    networks:
      - app-network

  frontend:
    build:
      context: ./  # Path to the directory containing your React.js frontend Dockerfile
    ports:
      - "3000:80"  # Expose React.js frontend on port 3000
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your Nginx config file
    ports:
      - "80:80"  # Expose Nginx on port 80
      - "443:443"  # Expose Nginx on port 443 for HTTPS
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge