version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Update with the actual name of your backend Dockerfile
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    volumes:
      - ./certificate:/next-care/one-health/certificate  # Mount certificate directory for SSL
    depends_on:
      - skincare  # If you have a database service, replace 'database' with its name

  #frontend:
    #build:
      #context: ./frontend/SkinWebapp_Admin
     # dockerfile: Dockerfile_Frontend  # Update with the actual name of your frontend Dockerfile
    #ports:
     # - "3000:80"  # Map container port 80 to host port 3000

  frontend:
    build:
      context: ./frontend/SkinWebapp_Admin
      dockerfile: Dockerfile_Frontend
    ports:
      - "3000:8000"
    volumes:
      - ./certificate:/next-care/one-health/certificate  # Mount certificate directory for SSL

  skincare:  # If you have a database service, define it here
    image: mysql:latest  # Example for MySQL
    ports:
      - "3306:3306"  # Map container port 3306 to host port 3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: skincare
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345678
      
      
